info:
  app:
    name: dgcol-ista
    description: Ista Microservice

server:
  port: 8081
  
grpc:
  server:
    port: 9091

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  grpc:
    jpa:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
      username: SA
      password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
